### ISSUE TITLE
Recommend a method for consuming the manifest file

### ISSUE THREAD

**Issue by mjackson** [mjackson/broccoli-rev#1]
The README should contain a recommended method for consuming the manifest file, like [gulp-rev has](https://github.com/sindresorhus/gulp-rev/blob/master/integration.md), except that I'm not sure the best way to do it.

Currently, the `rev-manifest.json` file is added to the `destDir` when `broccoli-rev` runs. Ideally it would be easy to specify another tree with an HTML template, for example, that contains references to the revved files. Then we could show how to use a templating engine like Handlebars together with the manifest file to generate the appropriate paths to the revved files, and trash the manifest file afterwards.

In a task-based system this is fairly straightforward because we can make sure the task that generates the manifest runs before the one that needs to use it. However, being new to broccoli I'm still learning to structure code without explicit tasks.

@joliss Would you have any suggestions about the best way to do this? Thank you in advance! :)

**Comment by joliss** [comment]
I'm unsure about this. As I mention in http://youtu.be/PEb4BiXH4bE?t=28m27s, I think the hard part is the URL rewriting, so you'll probably want to talk to whoever manages code for that (i.e. functions like `<%= image_path %>` or `image-url(...)`) how they want to consume manifests.

**Comment by mjackson** [comment]
@joliss Thanks for commenting!

I went ahead and suggested a method that could work in a very common scenario, but chose to implement it as a separate plugin so that users can continue to consume the raw `rev-manifest.json` file if they choose using some other tool.

**Comment by Climax777** [comment]
The manifest is only one part. Say for instance I want to concatenate all javascript files in a vendor folder. Typically in code one would include each one separately during development. However, during pre-production, one would want to concat + minify them and add rev suffixes.

That in itself is not a problem. But the "newly" created concatenated vendor file cannot automatically be injected, because it is not a 1:1 reference. Some concept of a bundle must be incorporated. This can either be done per application (link bundle to manifest entry(s) during production, or use each of the bundle during dev), or some plugin for broccoli might be an option.

What do you think?

**Comment by Climax777** [comment]
To elaborate on my previous post...

Consider this server side template

``` hbs
<!doctype html>
<html>
    <head>
        <title>My App</title>
        {{ cssBundle('vendor') }}
        <!-- becomes during dev... -->
        <!--- <link rel="stylesheet" href="file1.css"> -->
        <!--- <link rel="stylesheet" href="file2.css"> -->
        <!--- <link rel="stylesheet" href="file3.css"> -->
        <!--- <link rel="stylesheet" href="file4.css"> -->
        <!-- becomes during prod (after a preprod build phase)... -->
        <!--- <link rel="stylesheet" href="vendor-1234556.css"> -->
    </head>
    <body>
    </body>
</html>
```

During development, the template helper (say Swig) will look at the bundle name, look it up in its mapping to source files and produce the link tags.

During production however, the server side code parses the manifest file, consolidates it with a bundle name, and produce the single link file, with cache-busting digest suffix.

I am willing to help in writing such a plugin. I will need some guidance as to whether this must be a broccoli plugin, general node module, or some snippet.
